version: "3"

services:
  express-backend:
    container_name: fullpower-stack-backend
    build:
      context: .
      dockerfile: ./apps/backend/express/Dockerfile
    restart: always
    ports:
      - 4000:4000
    networks:
      - app_network
  # nextjs:
  #   container_name: fullpower-stack-nextjs
  #   build:
  #     context: .
  #     dockerfile: ./apps/nextjs/Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app_network

  vite:
    container_name: fullpower-stack-vite
    build:
      context: .
      dockerfile: ./apps/vite/Dockerfile
    restart: always
    ports:
      - 5173:5173
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    # external: true